apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmgate.fullname" . }}-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "helmgate.fullname" . }}-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "helmgate.fullname" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helmgate.fullname" . }}-frontend
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "helmgate.fullname" . }}-frontend
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      nodePort: {{ .Values.frontend.service.nodePort }}
