apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helmgate.fullname" . }}-secrets
type: Opaque
stringData:
  SECRET_KEY: "change-me-in-production"
  OPENROUTER_API_KEY: {{ .Values.backend.secrets.openrouterApiKey | quote }}
  GROQ_API_KEY: {{ .Values.backend.secrets.groqApiKey | quote }}
  TELEGRAM_ALERT_TOKEN: {{ .Values.backend.secrets.telegramAlertToken | quote }}
  TELEGRAM_ALERT_CHAT_ID: {{ .Values.backend.secrets.telegramAlertChatId | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
